# Generated by Django 4.2.6 on 2023-11-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroapp', '0005_contact_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='horoscopedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('day', models.IntegerField()),
                ('horoscope', models.CharField()),
            ],
            options={
                'db_table': 'Horoscope_table',
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
