# Generated by Django 4.2.6 on 2023-11-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroapp', '0006_horoscopedb_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='zodiacdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_month', models.CharField(max_length=255)),
                ('birth_day', models.IntegerField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('astro_sign', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Zodiac_sign',
            },
        ),
    ]
