# Generated by Django 4.2.6 on 2023-11-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroapp', '0007_zodiacdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=225)),
                ('lastname', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'contact_page',
            },
        ),
    ]
